import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { client } from '../libs/client'
import styles from '../styles/Home.module.scss'
import { NewsItem } from '../types/news'

type Props = {
  news: Array<NewsItem>
}

const Home: NextPage<Props> = (props) => {
  const { news } = props
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {news.map((item) => (
            <li key={item.id}>
              <Link href={`news/${item.id}`}>
                <a>{item.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({ endpoint: 'news' })
  return {
    props: {
      news: data.contents,
    },
  }
}
export default Home
